#!/bin/sh
export TOOLCHAIN=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=aarch64-linux-android
export API=21
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export PREFIX=$TOOLCHAIN/sysroot/usr
export CFLAGS="$CFLAGS -g"
./configure --host=$TARGET --prefix=$PREFIX --libdir=$PREFIX/lib/$TARGET/$API --disable-static
